### PR TITLE
Update A.java

### PR DESCRIPTION
**Pull request by sachinbhujbal**
called funtion using object .   by creating a 3 access  modifire. plz update this coz its my 1st contrubution in my life😅.hop you like my contrubution.

### CODE REVIEW

**Comment by sachinbhujbal** [comment]
hope u like it.

**Review by sachinbhujbal — COMMENTED** [review]
nice

**Comment by dipraj-howlader** [comment]
Ok, I will merge it, and thank you..but I didn't want to show the result actually..But Thank you for checking my code.

**Comment by sachinbhujbal** [comment]
thank you very much for that your all codes which makes for the reference codes to all learners.
i'll try of your another codes which really helpful to generate logics😅..again thanks for that opportunity.

**Pull request merged**
